### Instrospection (Types)

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

{"operationName":null,"variables":{},"query":"{\n  __schema {\n    types {\n      name\n      description\n      fields {\n        name\n        description\n      }\n    }\n  }\n}\n"}

### Instrospection (Queries)

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

{"operationName":null,"variables":{},"query":"{\n  __schema {\n    queryType {\n      name\n      description\n      fields {\n        name\n        description\n        args {\n          name\n          description\n        }\n      }\n    }\n  }\n}\n"}

### Introspection (Mutations)

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

{"operationName":null,"variables":{},"query":"{\n  __schema {\n    mutationType {\n      name\n      description\n      fields {\n        name\n        description\n        args {\n          name\n          description\n        }\n      }\n    }\n  }\n}\n"}

### Get Jobs

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

{"operationName":"jobQuery","variables":{},"query":"query jobQuery {\n  jobs {\n    version\n    name\n    status\n    hash\n    duration\n    entrypoint\n    __typename\n  }\n}\n"}

### Get Job by Name

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

{"operationName":"jobQuery","variables":{},"query":"query jobQuery {\n  getJobById(jobName: \"stringifyJson\") {\n    version\n    name\n    status\n    hash\n    duration\n    entrypoint\n    __typename\n  }\n}\n"}
