

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __schema {
    queryType {
      name
    }
    types {
      name
    }
  }
}

### Get types names from schema

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __schema {
    types {
      name
      fields {
        name
        description
        type { 
          name
          kind
        }
        args { 
          name
          type { 
            name
            kind 
            ofType { 
              name
              kind
            }
          }
        }
      }
    }
  }
}

### Get job schema

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __type(name: "Job") {
      name
      fields {
        name
        description
        type { 
          name
          kind
        }
        args { 
          name
          type { 
            name
            kind 
            ofType { 
              name
              kind
            }
          }
        }
      }
  }
}

### Get JobTask schema

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __type(name: "JobTask") {
    name
    fields {
      name
      type {
        kind
      }
      description
    }
  }
}

### Getting job arguments schema

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __type(name: "jobArgs") {
    name
    fields {
      name
      type {
        kind
      }
      description
    }
  }
}


### Get Jobs

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query jobQuery {
    jobs {
        version
        name
        status
        hash
        duration
        entrypoint
    }
}


### Get Mutations schema


### Get job schema

POST http://localhost:8080/graphql HTTP/1.1
content-type: application/json

query {
  __type(name: "jobMutation") {
      name
      fields {
        name
        description
        type { 
          name
          kind
        }
        args { 
          name
          type { 
            name
            kind 
            ofType { 
              name
              kind
            }
          }
        }
      }
  }
}


### Creating new job example request

POST http://localhost:8080/api/graphql HTTP/1.1
content-type: application/json

mutation {
  createJobType(input: {
    name: "example",
    args: [{name: "hello", value: "hello"}, {name: "world", value: "world"}],
    duration: "PT15S",
    entrypoint: "FirstTask",
    tasks: [
		{
			name: "FirstTask",
			script: "logger.info(hello + ' ' + world);",
			onSuccess: "",
			onFailure: ""
		}
	]
  }) {
    name
    args {
    	name
    	value
    }
  }
}

